### ISSUE TITLE
Killer field is still showing display codes

### ISSUE THREAD

**Issue by PowerSchill** [PowerSchill/minecraft-app#21]
Discovered that the codes in the fields are color codes. 

**Example:**
`2016-06-29T17:02:19-0700 name=DeathEvent event_id= game_time=15618077 world=SplunkMadScience x=-357 y=80 z=458 action=mob_died killer=§4Meson3902§r victim=Creeper damage_source=PROJECTILE server=SplunkCraftMadScience`

**Comment by PowerSchill** [comment]
Plan is to implement a utility function for handling the color codes appropriately.

**Comment by TheProducer835** [comment]
The color codes are the results of plugins being implemented. (in this case, Essentials, EssentialsX and PermissionsX) which all have an effect on the player name visualization. When you work on that we should turn off and turn on various plugins so that we can decide what to support in the plugin and what to suggest cleaning with field extraction.

**Comment by PowerSchill** [comment]
Issue fixed with commit a5a329f013a5536b729e67ac7b9c8c0deebaa86f
